# Generated by Django 6.0.1 on 2026-01-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance_miles', models.FloatField()),
                ('total_driving_time_mins', models.FloatField()),
                ('pickup_time_mins', models.FloatField()),
                ('current_cycle_hour', models.FloatField(default=0.0)),
            ],
        ),
    ]
